### ISSUE TITLE
Put articles (profile and invesment pages) inside a frame

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Web-Site#17]
Only in pages 'proflie' and 'investment', put the articles inside a frame.
'profile' page - "PHILOSOPHY" article: 
![image](https://user-images.githubusercontent.com/26923359/31053008-91548078-a69b-11e7-81d4-97e95dc2c55d.png)

'Investment' page - article under icons:
![image](https://user-images.githubusercontent.com/26923359/31053018-082c9adc-a69c-11e7-9609-e96d9f0c6a30.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev there's a design for this one which you can get from @talovdat.

**Comment by talovdat** [comment]
Sent the design to developers.way2cu
