### ISSUE TITLE
Change the look of the icons - investment page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Web-Site#22]
Change the look of the icons - investment page 
Current showing: 
![image](https://user-images.githubusercontent.com/26923359/31054044-a63c56a2-a6b2-11e7-82f5-7d09d14c8ed1.png)

How it seposed to show:
![image](https://user-images.githubusercontent.com/26923359/31054047-c1aeefb2-a6b2-11e7-9cc2-e091879efb2e.png)

**Comment by MeanEYE** [comment]
Did Michael prepare new ones?

**Comment by talovdat** [comment]
I sent an email which Michael sent, claiming it has the design and link to
the drive where you can find the icons.
So according to Michael, he did prepare new ones.

**Comment by MeanEYE** [comment]
Okay.
