### ISSUE TITLE
Mobile version menu is broken

### ISSUE THREAD

**Issue by VladimirWebDev** [Way2CU/IBI-Web-Site#24]
Main menu on mobile version is not working properly.

**Comment by MeanEYE** [comment]
Additional explanation is required.

**Comment by VladimirWebDev** [comment]
![image](https://user-images.githubusercontent.com/25882157/31320109-2b435f78-ac6f-11e7-8ab1-82f39221de2e.png)

Div containing menu is visible, menu icon is hidden bellow and can't be clicked.
This is landing page screenshot. 
This is different from designed menu.

![image](https://user-images.githubusercontent.com/25882157/31320145-d47232ea-ac6f-11e7-941e-26a0f15fe0b2.png)
This is design from Drive.
Probably there are changes since currently menu has 4 main categories with sub categories.

**Comment by MeanEYE** [comment]
Check if the mobile menu has "mobile_menu" class.
