### ISSUE TITLE
Change the logo

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Web-Site#37]
The logo needs to change.
A new logo will be provided tomorrow.

**Comment by MeanEYE** [comment]
Two hours left @talovdat before you provide new logo.

**Comment by talovdat** [comment]
Client claimed that his designer called in seek and ask to provide it tomorrow. 
So, hopefully, a new logo will be provided tomorrow.

**Comment by talovdat** [comment]
Logo has been sent to developers email address. 
White logo goes in the home page.
Blue logo goes in the rest of the pages.

**Comment by MeanEYE** [comment]
@VladimirWebDev we got PNG files. Wait for @talovdat to get back to us regarding SVG version. I'd prefer that one.
