### ISSUE TITLE
'News & Insights' headline shuold have regular i 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Web-Site#48]
![image](https://user-images.githubusercontent.com/26923359/33326746-6e50e8a0-d45e-11e7-9695-4f68deee8a8f.png)

**Comment by MeanEYE** [comment]
Why? Isn't grammar a thing anymore?

**Comment by talovdat** [comment]
It should match the 'News & Insights'

**Comment by MeanEYE** [comment]
Rather the other way around, _News & Insights_ should match _About us_ in it's capitalization. Unless both client and "people who think they know grammar" insist on writing the wrong thing.

**Comment by talovdat** [comment]
'News & Insights' headline should have regular i as Mladen pointed out. 
'About us' stays the same.
