### ISSUE TITLE
Contact and Management pages breaks at the bottom 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Web-Site#57]
Contact and management pages are braking at the bottom.
this issue applies only to Samsung monitors (Monitor s24E450)
                                                                        Resolution 1920 x 1080 
Google Chrome browser 

Image of the issue:
![image](https://user-images.githubusercontent.com/26923359/34671242-79b0d78e-f482-11e7-8b25-a9107bb1d119.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev this is most likely some ghost margin as it appears only on Chrome. Or at least that's what it looks like. This can also sometimes be the effect of `display: inline-block` or something similar. It appears only on few pages so it's probably either related to the page height or content on page.

**Comment by MeanEYE** [comment]
Site is located at http://ibi-ils.com

**Comment by VladimirWebDev** [comment]
Currently on two pages i can see this issue (Event updates and Research), which doesn't have content inside section so footer is pulled up. I set min height of section so in this cases footer stays where it should be.
