### ISSUE TITLE
Add ordering rule 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Web-Site#61]
Pages: 
http://ibi-ils.com/media
http://ibi-ils.com/events
http://ibi-ils.com/research

The client is adding articles chronologically so each new article should be automatically first from top left. 
![image](https://user-images.githubusercontent.com/26923359/36378532-dc7bf372-1583-11e8-9786-23702c36fc09.png)

So either ordering by text_id or each new article should show as first (top left) on those pages.

**Comment by MeanEYE** [comment]
This can be fixed by using `order_by="id"` and `order_asc="0"` attributes when calling `cms:module action="show_list"`.
