### ISSUE TITLE
Article structure - events page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/IBI-Web-Site#62]
URL: http://ibi-ils.com/events

Each new article that created on /events should have the same structure as the articles on /media - meaning the READ MORE button should open a link and not an inside article. 

![image](https://user-images.githubusercontent.com/26923359/36431871-640f65e8-1661-11e8-9820-ce84765240bf.png)

Image took from events page.

**Comment by MeanEYE** [comment]
Also @VladimirWebDev container for text should have `max-height` set. On other pages, text leaks over "Read more", which is a bug.

Edit: Reported as issue #64
